--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2 (Debian 15.2-1.pgdg110+1)
-- Dumped by pg_dump version 15.3 (Ubuntu 15.3-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO "user";

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO "user";

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO "user";

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO "user";

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO "user";

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO "user";

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: autoria_cars; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.autoria_cars (
    id integer NOT NULL,
    url character varying NOT NULL,
    profile_name character varying,
    phone_number character varying NOT NULL,
    title character varying NOT NULL,
    price integer NOT NULL,
    mileage integer NOT NULL,
    image_url character varying,
    image_count integer,
    car_number character varying,
    datetime_crawling timestamp with time zone NOT NULL
);


ALTER TABLE public.autoria_cars OWNER TO "user";

--
-- Name: autoria_cars_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.autoria_cars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.autoria_cars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: autoria_task; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.autoria_task (
    id integer NOT NULL,
    time_created timestamp with time zone NOT NULL
);


ALTER TABLE public.autoria_task OWNER TO "user";

--
-- Name: autoria_task_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.autoria_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.autoria_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO "user";

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_clockedschedule; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.django_celery_beat_clockedschedule (
    id integer NOT NULL,
    clocked_time timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO "user";

--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_clockedschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_crontabschedule; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.django_celery_beat_crontabschedule (
    id integer NOT NULL,
    minute character varying(240) NOT NULL,
    hour character varying(96) NOT NULL,
    day_of_week character varying(64) NOT NULL,
    day_of_month character varying(124) NOT NULL,
    month_of_year character varying(64) NOT NULL,
    timezone character varying(63) NOT NULL
);


ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO "user";

--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_crontabschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_intervalschedule; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.django_celery_beat_intervalschedule (
    id integer NOT NULL,
    every integer NOT NULL,
    period character varying(24) NOT NULL
);


ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO "user";

--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_intervalschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task character varying(200) NOT NULL,
    args text NOT NULL,
    kwargs text NOT NULL,
    queue character varying(200),
    exchange character varying(200),
    routing_key character varying(200),
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_expire_seconds_check CHECK ((expire_seconds >= 0)),
    CONSTRAINT django_celery_beat_periodictask_priority_check CHECK ((priority >= 0)),
    CONSTRAINT django_celery_beat_periodictask_total_run_count_check CHECK ((total_run_count >= 0))
);


ALTER TABLE public.django_celery_beat_periodictask OWNER TO "user";

--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_periodictask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_periodictasks OWNER TO "user";

--
-- Name: django_celery_beat_solarschedule; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.django_celery_beat_solarschedule (
    id integer NOT NULL,
    event character varying(24) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL
);


ALTER TABLE public.django_celery_beat_solarschedule OWNER TO "user";

--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_solarschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO "user";

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO "user";

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO "user";

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add cars	7	add_cars
26	Can change cars	7	change_cars
27	Can delete cars	7	delete_cars
28	Can view cars	7	view_cars
29	Can add task	8	add_task
30	Can change task	8	change_task
31	Can delete task	8	delete_task
32	Can view task	8	view_task
33	Can add crontab	9	add_crontabschedule
34	Can change crontab	9	change_crontabschedule
35	Can delete crontab	9	delete_crontabschedule
36	Can view crontab	9	view_crontabschedule
37	Can add interval	10	add_intervalschedule
38	Can change interval	10	change_intervalschedule
39	Can delete interval	10	delete_intervalschedule
40	Can view interval	10	view_intervalschedule
41	Can add periodic task	11	add_periodictask
42	Can change periodic task	11	change_periodictask
43	Can delete periodic task	11	delete_periodictask
44	Can view periodic task	11	view_periodictask
45	Can add periodic tasks	12	add_periodictasks
46	Can change periodic tasks	12	change_periodictasks
47	Can delete periodic tasks	12	delete_periodictasks
48	Can view periodic tasks	12	view_periodictasks
49	Can add solar event	13	add_solarschedule
50	Can change solar event	13	change_solarschedule
51	Can delete solar event	13	delete_solarschedule
52	Can view solar event	13	view_solarschedule
53	Can add clocked	14	add_clockedschedule
54	Can change clocked	14	change_clockedschedule
55	Can delete clocked	14	delete_clockedschedule
56	Can view clocked	14	view_clockedschedule
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$600000$yNSwPCk8z1NCoL02c5vJFY$hSYZOZI/LtIos08B8P4UYnx7OWjqMdjVLcna7LB9tG8=	2023-05-22 14:36:02.98182+00	t	admin				t	t	2023-05-22 14:35:45.669408+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: autoria_cars; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.autoria_cars (id, url, profile_name, phone_number, title, price, mileage, image_url, image_count, car_number, datetime_crawling) FROM stdin;
1	https://auto.ria.com/uk/auto_bmw_x3_34368684.html	 Нет Имени	38 (093) 201 03 42	BMW X3 2018	41900	102000	https://cdn3.riastatic.com/photosnew/auto/photo/bmw_x3__494048328f.webp	1	BH 4534 PH 	2023-05-22 14:37:41.342886+00
2	https://auto.ria.com/uk/auto_audi_a7_sportback_33317678.html	 Руслан Зозук	38 (097) 777 09 35	Audi A7 Sportback 2014	29999	189000	https://cdn1.riastatic.com/photosnew/auto/photo/audi_a7-sportback__483194141f.webp	1	BC 8900 OC 	2023-05-22 14:37:41.344788+00
3	https://auto.ria.com/uk/auto_renault_kangoo_34520697.html	 Микола	38 (097) 492 47 32	Renault Kangoo 2009	6300	288000	https://cdn1.riastatic.com/photosnew/auto/photo/renault_kangoo__497049351f.webp	1	AC 8682 BE 	2023-05-22 14:37:41.345892+00
4	https://auto.ria.com/uk/auto_acura_mdx_34519282.html	 Олег	38 (097) 960 59 28	Acura MDX 2018	33900	61000	https://cdn3.riastatic.com/photosnew/auto/photo/acura_mdx__497012683f.webp	1	BX 9799 CO 	2023-05-22 14:37:42.562015+00
5	https://auto.ria.com/uk/auto_skoda_fabia_34517016.html	 Назарий	38 (097) 903 00 25	Skoda Fabia 2010	7800	178000	https://cdn0.riastatic.com/photosnew/auto/photo/skoda_fabia__496956785f.webp	1	AT 1500 HC 	2023-05-22 14:37:45.229683+00
6	https://auto.ria.com/uk/auto_bmw_3_series_34510236.html	 Ім'я Не Вказано	38 (050) 849 54 59	BMW 3 Series 2013	13900	240000	https://cdn3.riastatic.com/photosnew/auto/photo/bmw_3-series__496782808f.webp	1	\N	2023-05-22 14:37:45.231285+00
7	https://auto.ria.com/uk/auto_nissan_qashqai_34470835.html	 Александр	38 (063) 075 72 09	Nissan Qashqai 2008	9700	120000	https://cdn1.riastatic.com/photosnew/auto/photo/nissan_qashqai__495722261f.webp	1	BH 1395 HA 	2023-05-22 14:38:11.34598+00
8	https://auto.ria.com/uk/auto_mercedes_benz_gle_class_34513556.html	 Игорь Янович	38 (066) 562 63 64	Mercedes-Benz GLE-Class 2018	42500	207000	https://cdn2.riastatic.com/photosnew/auto/photo/mercedes-benz_gle-class__496870537f.webp	1	\N	2023-05-22 14:38:11.346733+00
9	https://auto.ria.com/uk/auto_mercedes_benz_gle_class_34486563.html	 Виктор	38 (050) 758 88 88	Mercedes-Benz GLE-Class 2017	63000	91000	https://cdn0.riastatic.com/photosnew/auto/photo/mercedes-benz_gle-class__496121145f.webp	1	HH 0509 HH 	2023-05-22 14:38:11.347312+00
10	https://auto.ria.com/uk/auto_mega_mnl_34143577.html	\N	38 (095) 179 00 00	MEGA MNL 60 m3 2023	58300	1000	https://cdn2.riastatic.com/photosnew/auto/photo/mega_mnl__487309832f.webp	1	\N	2023-05-22 14:38:11.348287+00
11	https://auto.ria.com/uk/auto_land_rover_range_rover_evoque_34180483.html	 Александр	38 (067) 484 84 48	Land Rover Range Rover Evoque 2019	44900	26000	https://cdn4.riastatic.com/photosnew/auto/photo/land-rover_range-rover-evoque__494690609f.webp	1	BH 1984 OM 	2023-05-22 14:38:11.348781+00
12	https://auto.ria.com/uk/auto_volkswagen_passat_alltrack_34453740.html	 Vadym	38 (098) 223 35 67	Volkswagen Passat Alltrack 2019	31300	95000	https://cdn2.riastatic.com/photosnew/auto/photo/volkswagen_passat-alltrack__495256522f.webp	1	\N	2023-05-22 14:38:11.349297+00
13	https://auto.ria.com/uk/auto_daf_xf_105_34485265.html	 Дмитро	38 (067) 531 80 00	DAF XF 105 460 2010	20999	1270000	https://cdn2.riastatic.com/photosnew/auto/photo/daf_xf-105__496090162f.webp	1	\N	2023-05-22 14:38:11.349739+00
14	https://auto.ria.com/uk/auto_volkswagen_golf_plus_34500888.html	 Виталий	38 (098) 381 68 38	Volkswagen Golf Plus 2008	7000	260000	https://cdn1.riastatic.com/photosnew/auto/photo/volkswagen_golf-plus__496483431f.webp	1	BM 5751 EB 	2023-05-22 14:38:11.35065+00
15	https://auto.ria.com/uk/auto_porsche_macan_33821563.html	\N	38 (097) 455 08 35	Porsche Macan Crayon 2022	79999	1000	https://cdn1.riastatic.com/photosnew/auto/photo/porsche_macan__495849151f.webp	1	\N	2023-05-22 14:38:11.3511+00
16	https://auto.ria.com/uk/auto_bmw_x3_34509616.html	 Мирослав	38 (067) 256 19 55	BMW X3 2011	17400	254000	https://cdn1.riastatic.com/photosnew/auto/photo/bmw_x3__496763576f.webp	1	\N	2023-05-22 14:38:11.351808+00
17	https://auto.ria.com/uk/auto_nissan_x_trail_34505969.html	 Богдан	38 (073) 184 86 68	Nissan X-Trail 2014	16350	200000	https://cdn2.riastatic.com/photosnew/auto/photo/nissan_x-trail__496613442f.webp	1	\N	2023-05-22 14:38:11.352218+00
18	https://auto.ria.com/uk/auto_porsche_panamera_34351270.html	 Роман	38 (098) 150 83 15	Porsche Panamera 2019	119000	20000	https://cdn3.riastatic.com/photosnew/auto/photo/porsche_panamera__492633003f.webp	1	KA 3030 KA 	2023-05-22 14:38:11.352983+00
19	https://auto.ria.com/uk/auto_bmw_x6_34482226.html	 Владимир	38 (063) 650 73 43	BMW X6 2016	44000	210000	https://cdn3.riastatic.com/photosnew/auto/photo/bmw_x6__495951013f.webp	1	AI 0356 OP 	2023-05-22 14:38:11.353559+00
20	https://auto.ria.com/uk/auto_volkswagen_transporter_34361235.html	\N	38 (068) 020 38 86	Volkswagen Transporter 2002	7400	700000	https://cdn0.riastatic.com/photosnew/auto/photo/volkswagen_transporter__492550980f.webp	1	AC 9675 CB 	2023-05-22 14:38:11.353845+00
21	https://auto.ria.com/uk/auto_volkswagen_golf_gti_34149329.html	 Андрей	38 (097) 709 77 36	Volkswagen Golf GTI 2012	9200	263000	https://cdn0.riastatic.com/photosnew/auto/photo/volkswagen_golf-gti__487465100f.webp	1	\N	2023-05-22 14:38:11.354134+00
22	https://auto.ria.com/uk/auto_tesla_model_3_33583250.html	\N	38 (063) 031 08 76	Tesla Model 3 2020	33300	105000	\N	0	\N	2023-05-22 14:38:11.355142+00
23	https://auto.ria.com/uk/auto_renault_premium_34401600.html	 Serhii	38 (096) 789 88 90	Renault Premium 2010	15700	660000	https://cdn1.riastatic.com/photosnew/auto/photo/renault_premium__493896886f.webp	1	\N	2023-05-22 14:38:11.355386+00
24	https://auto.ria.com/uk/auto_volkswagen_id_4_crozz_34485328.html	\N	38 (063) 850 06 06	Volkswagen ID.4 Crozz 2022	31795	1000	https://cdn4.riastatic.com/photosnew/auto/photo/volkswagen_id-4-crozz__496091334f.webp	1	\N	2023-05-22 14:38:11.355649+00
25	https://auto.ria.com/uk/auto_mazda_cx_9_34485661.html	 Богдан	38 (099) 280 65 60	Mazda CX-9 2008	9300	165000	https://cdn2.riastatic.com/photosnew/auto/photo/mazda_cx-9__496099577f.webp	1	KA 5228 AB 	2023-05-22 14:38:11.355907+00
26	https://auto.ria.com/uk/auto_toyota_land_cruiser_prado_34363912.html	 Андрей Александрович	38 (093) 725 84 88	Toyota Land Cruiser Prado 2018	43000	91000	https://cdn2.riastatic.com/photosnew/auto/photo/toyota_land-cruiser-prado__492941697f.webp	1	KA 3211 IT 	2023-05-22 14:38:11.356662+00
27	https://auto.ria.com/uk/auto_volkswagen_id_4_crozz_34502959.html	\N	38 (063) 850 06 06	Volkswagen ID.4 Crozz 2022	31995	1000	https://cdn0.riastatic.com/photosnew/auto/photo/volkswagen_id-4-crozz__496538165f.webp	1	\N	2023-05-22 14:38:11.356938+00
28	https://auto.ria.com/uk/auto_mercedes_benz_sprinter_34398349.html	 Игорь	38 (073) 050 24 10	Mercedes-Benz Sprinter 2011	26900	563000	https://cdn2.riastatic.com/photosnew/auto/photo/mercedes-benz_sprinter__493811677f.webp	1	\N	2023-05-22 14:38:11.357188+00
29	https://auto.ria.com/uk/auto_audi_q7_34373944.html	 Олександр Сергійович	38 (097) 177 08 62	Audi Q7 2017	35900	89000	https://cdn2.riastatic.com/photosnew/auto/photo/audi_q7__497087167f.webp	1	\N	2023-05-22 14:38:11.357475+00
30	https://auto.ria.com/uk/auto_daewoo_lanos_34343600.html	 Анна	38 (098) 833 43 09	Daewoo Lanos se 2007	2500	347000	https://cdn0.riastatic.com/photosnew/auto/photo/daewoo_lanos__492434990f.webp	1	AI 4618 MC 	2023-05-22 14:38:11.357709+00
31	https://auto.ria.com/uk/auto_audi_e_tron_34505126.html	\N	38 (067) 412 37 94	Audi e-tron 2019	59000	27000	https://cdn4.riastatic.com/photosnew/auto/photo/audi_e-tron__496593774f.webp	1	\N	2023-05-22 14:38:11.358273+00
32	https://auto.ria.com/uk/auto_renault_trafic_34308160.html	 Андрій	38 (067) 278 92 62	Renault Trafic 2016	13250	223000	https://cdn3.riastatic.com/photosnew/auto/photo/renault_trafic__495579148f.webp	1	\N	2023-05-22 14:38:11.358498+00
33	https://auto.ria.com/uk/auto_vaz_lada_21099_34493656.html	 Михайло	38 (093) 621 52 41	ВАЗ / Lada 21099 2008	1950	274000	https://cdn1.riastatic.com/photosnew/auto/photo/vaz-lada_21099__496301746f.webp	1	BC 3414 OC 	2023-05-22 14:38:41.351976+00
34	https://auto.ria.com/uk/auto_volkswagen_touareg_34455020.html	 Петрович	38 (073) 020 68 82	Volkswagen Touareg 2023	79999	1000	https://cdn2.riastatic.com/photosnew/auto/photo/volkswagen_touareg__495326972f.webp	1	\N	2023-05-22 14:38:41.352367+00
35	https://auto.ria.com/uk/auto_kia_sportage_34521433.html	 Сергій	38 (050) 457 37 83	Kia Sportage 2019	19500	63000	https://cdn2.riastatic.com/photosnew/auto/photo/kia_sportage__497069242f.webp	1	\N	2023-05-22 14:38:41.355677+00
36	https://auto.ria.com/uk/auto_skoda_superb_34425808.html	\N	38 (098) 708 19 19	Skoda Superb 2019	24555	191000	\N	0	\N	2023-05-22 14:38:41.357665+00
37	https://auto.ria.com/uk/auto_iveco_daily_gruz_34096167.html	\N	38 (098) 708 19 19	Iveco Daily груз. IS70CI2BA 2016	22999	287000	\N	0	\N	2023-05-22 14:38:41.358354+00
38	https://auto.ria.com/uk/auto_mercedes_benz_sprinter_33845303.html	 Иван	38 (050) 311 44 42	Mercedes-Benz Sprinter 2018	15450	278000	https://cdn3.riastatic.com/photosnew/auto/photo/mercedes-benz_sprinter__479867653f.webp	1	\N	2023-05-22 14:39:42.568842+00
39	https://auto.ria.com/uk/auto_daf_xf_105_34511630.html	 Игорь	38 (068) 557 36 70	DAF XF 105 elegance 2012	26750	735000	https://cdn0.riastatic.com/photosnew/auto/photo/daf_xf-105__496818745f.webp	1	\N	2023-05-22 14:39:42.569331+00
40	https://auto.ria.com/uk/auto_mitsubishi_outlander_34430304.html	 Valerii Oleksiichuk	38 (073) 077 88 83	Mitsubishi Outlander 2015	12900	180000	https://cdn1.riastatic.com/photosnew/auto/photo/mitsubishi_outlander__495694871f.webp	1	\N	2023-05-22 14:39:42.569811+00
41	https://auto.ria.com/uk/auto_nissan_qashqai_34510194.html	 Назарій	38 (063) 271 00 19	Nissan Qashqai 2009	8700	250000	https://cdn3.riastatic.com/photosnew/auto/photo/nissan_qashqai__496778318f.webp	1	BC 9254 IM 	2023-05-22 14:39:42.570806+00
42	https://auto.ria.com/uk/auto_peugeot_308_34409805.html	 Орест Чукла	38 (073) 217 91 00	Peugeot 308 2011	5800	149000	https://cdn2.riastatic.com/photosnew/auto/photo/peugeot_308__494106607f.webp	1	BC 0237 EP 	2023-05-22 14:39:42.57133+00
43	https://auto.ria.com/uk/auto_mazda_6_34511850.html	 Александр	38 (067) 374 77 88	Mazda 6 2015	16900	160000	https://cdn3.riastatic.com/photosnew/auto/photo/mazda_6__496820673f.webp	1	\N	2023-05-22 14:39:42.57189+00
44	https://auto.ria.com/uk/auto_mazda_6_34412897.html	 Сергій	38 (067) 475 77 03	Mazda 6 2015	13000	183000	https://cdn4.riastatic.com/photosnew/auto/photo/mazda_6__494792209f.webp	1	\N	2023-05-22 14:39:42.572388+00
45	https://auto.ria.com/uk/auto_porsche_panamera_34514987.html	 Юрій Вікторович Тимощицький	38 (095) 845 48 76	Porsche Panamera GTS 2012	40000	84000	\N	0	BK 9494 CM 	2023-05-22 14:39:42.572785+00
46	https://auto.ria.com/uk/auto_lexus_gx_33646115.html	 Даниил	38 (096) 477 66 39	Lexus GX 2006	15999	200000	https://cdn4.riastatic.com/photosnew/auto/photo/lexus_gx__488474204f.webp	1	BH 4950 PT 	2023-05-22 14:39:42.573431+00
47	https://auto.ria.com/uk/auto_bmw_5_series_34508123.html	 Игорь	38 (067) 363 88 11	BMW 5 Series 2014	22300	168000	\N	0	\N	2023-05-22 14:39:42.573897+00
48	https://auto.ria.com/uk/auto_bmw_4_series_34140894.html	 Александр	38 (098) 398 15 47	BMW 4 Series 2016	29444	84000	https://cdn0.riastatic.com/photosnew/auto/photo/bmw_4-series__487250010f.webp	1	\N	2023-05-22 14:39:42.574741+00
49	https://auto.ria.com/uk/auto_mercedes_benz_sprinter_33190539.html	 Лариса	38 (067) 507 25 65	Mercedes-Benz Sprinter 2005	8800	300000	https://cdn2.riastatic.com/photosnew/auto/photo/mercedes-benz_sprinter__463777527f.webp	1	\N	2023-05-22 14:39:42.575217+00
50	https://auto.ria.com/uk/auto_dodge_journey_34352505.html	 Василь Миколайович Сорохтей	38 (096) 294 30 35	Dodge Journey 2018	14500	106000	https://cdn0.riastatic.com/photosnew/auto/photo/dodge_journey__492663510f.webp	1	AM 3400 ET 	2023-05-22 14:39:42.575657+00
51	https://auto.ria.com/uk/auto_bmw_ix_34484800.html	 Юрій	38 (067) 007 99 99	BMW iX 2021	78000	10000	https://cdn4.riastatic.com/photosnew/auto/photo/bmw_ix__496078679f.webp	1	CE 2020 ZA 	2023-05-22 14:39:42.576105+00
52	https://auto.ria.com/uk/auto_mercedes_benz_sprinter_33779626.html	 Semen Zeltser	38 (067) 431 41 89	Mercedes-Benz Sprinter 2017	22500	135000	https://cdn3.riastatic.com/photosnew/auto/photo/mercedes-benz_sprinter__478290633f.webp	1	\N	2023-05-22 14:39:42.576531+00
53	https://auto.ria.com/uk/auto_mercedes_benz_glc_class_34474231.html	 Максим Миколайович Ситник	38 (050) 410 11 90	Mercedes-Benz GLC-Class 2021	52000	1000	https://cdn4.riastatic.com/photosnew/auto/photo/mercedes-benz_glc-class__495816069f.webp	1	\N	2023-05-22 14:39:42.57697+00
54	https://auto.ria.com/uk/auto_mercedes_benz_sprinter_34490532.html	 Константин	38 (067) 430 69 18	Mercedes-Benz Sprinter 2016	30900	275000	https://cdn1.riastatic.com/photosnew/auto/photo/mercedes-benz_sprinter__496224081f.webp	1	AB 0100 IB 	2023-05-22 14:39:42.57733+00
55	https://auto.ria.com/uk/auto_ford_fiesta_34474021.html	 Лёша	38 (066) 244 08 08	Ford Fiesta 2017	9800	176000	https://cdn4.riastatic.com/photosnew/auto/photo/ford_fiesta__496554479f.webp	1	KA 6627 HI 	2023-05-22 14:39:42.577908+00
56	https://auto.ria.com/uk/auto_mercedes_benz_sprinter_33817124.html	 Іван	38 (098) 024 46 63	Mercedes-Benz Sprinter 2018	35800	514000	https://cdn1.riastatic.com/photosnew/auto/photo/mercedes-benz_sprinter__496600186f.webp	1	AO 1531 HH 	2023-05-22 14:39:42.578263+00
57	https://auto.ria.com/uk/auto_mercedes_benz_sprinter_34387552.html	 Semen Zeltser	38 (067) 431 41 89	Mercedes-Benz Sprinter 2016	22900	317000	https://cdn0.riastatic.com/photosnew/auto/photo/mercedes-benz_sprinter__493534590f.webp	1	\N	2023-05-22 14:39:42.578601+00
58	https://auto.ria.com/uk/auto_audi_a6_34510954.html	 Олександр	38 (098) 312 33 33	Audi A6 2011	17900	253000	https://cdn1.riastatic.com/photosnew/auto/photo/audi_a6__496799651f.webp	1	AO 8001 HK 	2023-05-22 14:39:42.578949+00
59	https://auto.ria.com/uk/auto_nissan_leaf_33766379.html	 Віталій Булах	38 (099) 136 75 79	Nissan Leaf 2019	20800	77000	\N	0	AA 5834 ZA 	2023-05-22 14:39:42.579289+00
60	https://auto.ria.com/uk/auto_mazda_6_31686340.html	 Домінік	38 (066) 404 16 44	Mazda 6 2013	10300	240000	https://cdn3.riastatic.com/photosnew/auto/photo/mazda_6__429002823f.webp	1	AO 8168 HB 	2023-05-22 14:39:42.579618+00
61	https://auto.ria.com/uk/auto_volkswagen_touran_34507587.html	 Andriy	38 (068) 770 06 60	Volkswagen Touran 2012	9999	205000	https://cdn3.riastatic.com/photosnew/auto/photo/volkswagen_touran__496729433f.webp	1	\N	2023-05-22 14:39:42.579947+00
62	https://auto.ria.com/uk/auto_nissan_leaf_34490443.html	\N	38 (063) 190 40 01	Nissan Leaf 2014	9999	146000	\N	0	\N	2023-05-22 14:39:42.580283+00
63	https://auto.ria.com/uk/auto_daf_xf_105_34246123.html	\N	38 (095) 602 72 22	DAF XF 105 460 2011	17500	1160000	\N	0	\N	2023-05-22 14:39:42.5806+00
64	https://auto.ria.com/uk/auto_mercedes_benz_sprinter_34386846.html	 Semen Zeltser	38 (067) 431 41 89	Mercedes-Benz Sprinter 2018	29000	290000	https://cdn3.riastatic.com/photosnew/auto/photo/mercedes-benz_sprinter__493513898f.webp	1	\N	2023-05-22 14:39:42.580944+00
65	https://auto.ria.com/uk/auto_volkswagen_id_4_crozz_34451297.html	 Олексій	38 (095) 793 41 07	Volkswagen ID.4 Crozz 2022	31400	1000	https://cdn1.riastatic.com/photosnew/auto/photo/volkswagen_id-4-crozz__495199106f.webp	1	\N	2023-05-22 14:39:42.581473+00
66	https://auto.ria.com/uk/auto_audi_e_tron_33120149.html	 Александр	38 (067) 490 63 33	Audi e-tron 2019	59990	55000	https://cdn3.riastatic.com/photosnew/auto/photo/audi_e-tron__469354103f.webp	1	\N	2023-05-22 14:39:42.581825+00
67	https://auto.ria.com/uk/auto_daf_xf_105_34335300.html	 Дмитро Тарнопольський	38 (096) 209 90 08	DAF XF 105 105 2013	30490	610000	https://cdn1.riastatic.com/photosnew/auto/photo/daf_xf-105__496888976f.webp	1	\N	2023-05-22 14:39:42.582103+00
68	https://auto.ria.com/uk/auto_scania_r_450_34472113.html	 Вітя	38 (096) 671 57 77	Scania R 450 2014	39900	1050000	https://cdn2.riastatic.com/photosnew/auto/photo/scania_r-450__495758097f.webp	1	\N	2023-05-22 14:39:42.582642+00
69	https://auto.ria.com/uk/auto_toyota_land_cruiser_prado_34376729.html	 Юрій	38 (066) 444 55 55	Toyota Land Cruiser Prado 2019	46900	49000	https://cdn4.riastatic.com/photosnew/auto/photo/toyota_land-cruiser-prado__493243989f.webp	1	BC 9675 PI 	2023-05-22 14:39:42.583545+00
70	https://auto.ria.com/uk/auto_bmw_x5_34307178.html	\N	38 (067) 293 22 18	BMW X5 2016	24500	142000	https://cdn3.riastatic.com/photosnew/auto/photo/bmw_x5__491527363f.webp	1	\N	2023-05-22 14:39:42.583919+00
71	https://auto.ria.com/uk/auto_opel_vectra_34338437.html	 Ігор Мальханов	38 (098) 676 11 86	Opel Vectra 1990	1350	208000	https://cdn3.riastatic.com/photosnew/auto/photo/opel_vectra__492297503f.webp	1	\N	2023-05-22 14:39:42.584625+00
72	https://auto.ria.com/uk/auto_ford_explorer_34230731.html	\N	38 (050) 071 17 00	Ford Explorer 2016	21600	195000	https://cdn4.riastatic.com/photosnew/auto/photo/ford_explorer__489549744f.webp	1	AI 1700 ВК 	2023-05-22 14:39:42.585203+00
73	https://auto.ria.com/uk/auto_audi_a7_sportback_34361769.html	\N	38 (095) 505 00 06	Audi A7 Sportback 2012	15999	157000	https://cdn1.riastatic.com/photosnew/auto/photo/audi_a7-sportback__492885811f.webp	1	BH 8377 PO 	2023-05-22 14:39:42.585562+00
74	https://auto.ria.com/uk/auto_renault_kangoo_34517995.html	 Вова	38 (066) 374 79 49	Renault Kangoo 2016	12550	82000	https://cdn4.riastatic.com/photosnew/auto/photo/renault_kangoo__496982044f.webp	1	\N	2023-05-22 14:39:42.585903+00
75	https://auto.ria.com/uk/auto_nissan_x_trail_29894421.html	 Максим	38 (097) 554 37 17	Nissan X-Trail 2008	9500	250000	https://cdn0.riastatic.com/photosnew/auto/photo/nissan_x-trail__483543785f.webp	1	AE 7980 OP 	2023-05-22 14:39:42.586228+00
76	https://auto.ria.com/uk/auto_audi_a6_34515460.html	 Степан	38 (095) 407 57 21	Audi A6 2016	28500	109000	https://cdn0.riastatic.com/photosnew/auto/photo/audi_a6__496910975f.webp	1	AC 0630 HI 	2023-05-22 14:39:42.586612+00
77	https://auto.ria.com/uk/auto_volkswagen_t_roc_34514566.html	 Алексей	38 (093) 399 95 66	Volkswagen T-Roc 2019	25200	64000	https://cdn0.riastatic.com/photosnew/auto/photo/volkswagen_t-roc__496898190f.webp	1	AI 0111 MA 	2023-05-22 14:39:42.587003+00
78	https://auto.ria.com/uk/auto_honda_civic_34432969.html	 Nazar Yunko	38 (097) 094 12 29	Honda Civic 2015	13699	123000	https://cdn4.riastatic.com/photosnew/auto/photo/honda_civic__494736994f.webp	1	BC 2715 PB 	2023-05-22 14:39:42.587307+00
79	https://auto.ria.com/uk/auto_peugeot_3008_34511242.html	 Roman	38 (097) 653 49 21	Peugeot 3008 2011	8450	220000	https://cdn2.riastatic.com/photosnew/auto/photo/peugeot_3008__496803997f.webp	1	\N	2023-05-22 14:39:42.587635+00
80	https://auto.ria.com/uk/auto_fiat_doblo_gruz_34202574.html	 Max Kolisnyk	38 (067) 954 01 01	Fiat Doblo груз. 2009	7000	400000	\N	0	AE 1794 KT 	2023-05-22 14:39:45.233439+00
81	https://auto.ria.com/uk/auto_acura_mdx_32678226.html	 Aleksander	38 (050) 046 25 00	Acura MDX 2013	20999	118000	https://cdn2.riastatic.com/photosnew/auto/photo/acura_mdx__454740957f.webp	1	KA 5458 EH 	2023-05-22 14:39:45.233937+00
82	https://auto.ria.com/uk/auto_bmw_m8_33079906.html	 Діма	38 (096) 209 90 09	BMW M8 2019	120000	18000	https://cdn1.riastatic.com/photosnew/auto/photo/bmw_m8__487740436f.webp	1	\N	2023-05-22 14:40:12.573289+00
83	https://auto.ria.com/uk/auto_mitsubishi_pajero_sport_34522421.html	 Александр	38 (096) 600 17 34	Mitsubishi Pajero Sport 2019	32900	61000	https://cdn1.riastatic.com/photosnew/auto/photo/mitsubishi_pajero-sport__497095946f.webp	1	AE 0295 KX 	2023-05-22 14:40:15.301348+00
84	https://auto.ria.com/uk/auto_ford_focus_34521832.html	 Максим	38 (098) 042 24 04	Ford Focus 2017	8499	129000	https://cdn2.riastatic.com/photosnew/auto/photo/ford_focus__497081412f.webp	1	KA 8403 IO 	2023-05-22 14:40:25.933038+00
85	https://auto.ria.com/uk/auto_mercedes_benz_c_class_34325111.html	 Демид Шумаков	38 (098) 484 23 06	Mercedes-Benz C-Class 2014	20000	94000	https://cdn1.riastatic.com/photosnew/auto/photo/mercedes-benz_c-class__491967216f.webp	1	\N	2023-05-22 14:40:25.933361+00
86	https://auto.ria.com/uk/auto_nissan_x_trail_34344395.html	 Iren	38 (097) 628 80 34	Nissan X-Trail 2012	13899	180000	https://cdn2.riastatic.com/photosnew/auto/photo/nissan_x-trail__492453852f.webp	1	\N	2023-05-22 14:40:25.934419+00
87	https://auto.ria.com/uk/auto_porsche_cayenne_31760083.html	 Имя	38 (097) 275 33 21	Porsche Cayenne GTS 2008	15900	93000	https://cdn2.riastatic.com/photosnew/auto/photo/porsche_cayenne__493984037f.webp	1	\N	2023-05-22 14:40:25.935014+00
88	https://auto.ria.com/uk/auto_honda_civic_34395921.html	 Iren	38 (097) 628 80 34	Honda Civic 2011	6999	160000	https://cdn0.riastatic.com/photosnew/auto/photo/honda_civic__497072290f.webp	1	\N	2023-05-22 14:40:25.935917+00
89	https://auto.ria.com/uk/auto_volkswagen_tiguan_34520163.html	 Руслан	38 (093) 950 90 79	Volkswagen Tiguan 2011	13500	122000	https://cdn2.riastatic.com/photosnew/auto/photo/volkswagen_tiguan__497036857f.webp	1	\N	2023-05-22 14:40:42.572853+00
90	https://auto.ria.com/uk/auto_porsche_panamera_33213596.html	 Роман Владимирович	38 (068) 999 91 29	Porsche Panamera 2014	45700	119000	https://cdn1.riastatic.com/photosnew/auto/photo/porsche_panamera__464342161f.webp	1	KA 6368 HP 	2023-05-22 14:40:42.573619+00
91	https://auto.ria.com/uk/auto_toyota_rav4_34520988.html	 Пашка Михайлович Кльова	38 (063) 654 45 49	Toyota RAV4 2016	27000	112000	https://cdn2.riastatic.com/photosnew/auto/photo/toyota_rav4__497057717f.webp	1	\N	2023-05-22 14:40:42.574159+00
92	https://auto.ria.com/uk/auto_toyota_camry_34371449.html	 Віталій	38 (073) 000 73 77	Toyota Camry 2021	31333	1000	https://cdn1.riastatic.com/photosnew/auto/photo/toyota_camry__493868256f.webp	1	KA 3154 IT 	2023-05-22 14:40:42.992657+00
\.


--
-- Data for Name: autoria_task; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.autoria_task (id, time_created) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2023-05-22 14:36:19.251325+00	1	every 30 seconds	1	[{"added": {}}]	10	1
2	2023-05-22 14:36:21.633012+00	1	db: every 30 seconds	1	[{"added": {}}]	11	1
3	2023-05-22 14:36:33.197427+00	2	sheets: every 30 seconds	1	[{"added": {}}]	11	1
4	2023-05-22 14:36:49.564051+00	2	every day	1	[{"added": {}}]	10	1
5	2023-05-22 14:36:54.770244+00	3	manager: every day	1	[{"added": {}}]	11	1
\.


--
-- Data for Name: django_celery_beat_clockedschedule; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.django_celery_beat_clockedschedule (id, clocked_time) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_crontabschedule; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.django_celery_beat_crontabschedule (id, minute, hour, day_of_week, day_of_month, month_of_year, timezone) FROM stdin;
1	0	4	*	*	*	UTC
\.


--
-- Data for Name: django_celery_beat_intervalschedule; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.django_celery_beat_intervalschedule (id, every, period) FROM stdin;
1	30	seconds
2	1	days
\.


--
-- Data for Name: django_celery_beat_periodictask; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.django_celery_beat_periodictask (id, name, task, args, kwargs, queue, exchange, routing_key, expires, enabled, last_run_at, total_run_count, date_changed, description, crontab_id, interval_id, solar_id, one_off, start_time, priority, headers, clocked_id, expire_seconds) FROM stdin;
3	manager	autoria.tasks.manager_task	[]	{}	\N	\N	\N	\N	t	\N	0	2023-05-22 14:36:54.767581+00		\N	2	\N	f	\N	\N	{}	\N	\N
4	celery.backend_cleanup	celery.backend_cleanup	[]	{}	\N	\N	\N	\N	t	\N	0	2023-05-22 14:40:25.890543+00		1	\N	\N	f	\N	\N	{}	\N	43200
2	sheets	autoria.tasks.spreadsheets_worker	[]	{}	\N	\N	\N	\N	t	2023-05-22 14:40:42.970403+00	7	2023-05-22 14:41:11.291752+00		\N	1	\N	f	\N	\N	{}	\N	\N
1	db	autoria.tasks.car_db_worker	[]	{}	\N	\N	\N	\N	t	2023-05-22 14:41:12.583612+00	8	2023-05-22 14:41:12.654705+00		\N	1	\N	f	\N	\N	{}	\N	\N
\.


--
-- Data for Name: django_celery_beat_periodictasks; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.django_celery_beat_periodictasks (ident, last_update) FROM stdin;
1	2023-05-22 14:40:25.891188+00
\.


--
-- Data for Name: django_celery_beat_solarschedule; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.django_celery_beat_solarschedule (id, event, latitude, longitude) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	autoria	cars
8	autoria	task
9	django_celery_beat	crontabschedule
10	django_celery_beat	intervalschedule
11	django_celery_beat	periodictask
12	django_celery_beat	periodictasks
13	django_celery_beat	solarschedule
14	django_celery_beat	clockedschedule
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2023-05-22 14:35:28.512761+00
2	auth	0001_initial	2023-05-22 14:35:28.612186+00
3	admin	0001_initial	2023-05-22 14:35:28.6415+00
4	admin	0002_logentry_remove_auto_add	2023-05-22 14:35:28.647719+00
5	admin	0003_logentry_add_action_flag_choices	2023-05-22 14:35:28.654552+00
6	contenttypes	0002_remove_content_type_name	2023-05-22 14:35:28.666803+00
7	auth	0002_alter_permission_name_max_length	2023-05-22 14:35:28.683187+00
8	auth	0003_alter_user_email_max_length	2023-05-22 14:35:28.692492+00
9	auth	0004_alter_user_username_opts	2023-05-22 14:35:28.699684+00
10	auth	0005_alter_user_last_login_null	2023-05-22 14:35:28.707308+00
11	auth	0006_require_contenttypes_0002	2023-05-22 14:35:28.70946+00
12	auth	0007_alter_validators_add_error_messages	2023-05-22 14:35:28.716228+00
13	auth	0008_alter_user_username_max_length	2023-05-22 14:35:28.72535+00
14	auth	0009_alter_user_last_name_max_length	2023-05-22 14:35:28.732507+00
15	auth	0010_alter_group_name_max_length	2023-05-22 14:35:28.740178+00
16	auth	0011_update_proxy_permissions	2023-05-22 14:35:28.746665+00
17	auth	0012_alter_user_first_name_max_length	2023-05-22 14:35:28.761294+00
18	autoria	0001_initial	2023-05-22 14:35:28.790994+00
19	autoria	0002_alter_cars_car_number	2023-05-22 14:35:28.800295+00
20	autoria	0003_alter_cars_image_count_alter_cars_image_url_and_more	2023-05-22 14:35:28.806175+00
21	django_celery_beat	0001_initial	2023-05-22 14:35:28.828411+00
22	django_celery_beat	0002_auto_20161118_0346	2023-05-22 14:35:28.839099+00
23	django_celery_beat	0003_auto_20161209_0049	2023-05-22 14:35:28.847957+00
24	django_celery_beat	0004_auto_20170221_0000	2023-05-22 14:35:28.852375+00
25	django_celery_beat	0005_add_solarschedule_events_choices	2023-05-22 14:35:28.857991+00
26	django_celery_beat	0006_auto_20180322_0932	2023-05-22 14:35:28.876303+00
27	django_celery_beat	0007_auto_20180521_0826	2023-05-22 14:35:28.88469+00
28	django_celery_beat	0008_auto_20180914_1922	2023-05-22 14:35:28.900446+00
29	django_celery_beat	0006_auto_20180210_1226	2023-05-22 14:35:28.908832+00
30	django_celery_beat	0006_periodictask_priority	2023-05-22 14:35:28.916035+00
31	django_celery_beat	0009_periodictask_headers	2023-05-22 14:35:28.922531+00
32	django_celery_beat	0010_auto_20190429_0326	2023-05-22 14:35:29.017375+00
33	django_celery_beat	0011_auto_20190508_0153	2023-05-22 14:35:29.032625+00
34	django_celery_beat	0012_periodictask_expire_seconds	2023-05-22 14:35:29.041071+00
35	django_celery_beat	0013_auto_20200609_0727	2023-05-22 14:35:29.045776+00
36	django_celery_beat	0014_remove_clockedschedule_enabled	2023-05-22 14:35:29.050186+00
37	django_celery_beat	0015_edit_solarschedule_events_choices	2023-05-22 14:35:29.055246+00
38	django_celery_beat	0016_alter_crontabschedule_timezone	2023-05-22 14:35:29.061472+00
39	django_celery_beat	0017_alter_crontabschedule_month_of_year	2023-05-22 14:35:29.065599+00
40	django_celery_beat	0018_improve_crontab_helptext	2023-05-22 14:35:29.069746+00
41	sessions	0001_initial	2023-05-22 14:35:29.079255+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
01w3t2wz6aumoxm1jnd5ukvoyt58pdtq	.eJxVjDsOwjAQBe_iGll4_WMp6XOGyJ9dHEC2FCcV4u7IUgpo38y8t5jDvpV577TOSxZXocTpd4shPakOkB-h3ptMrW7rEuVQ5EG7nFqm1-1w_w5K6GXUnD0AI_uckvIWEdkQGxeBlCYTjOXEZwJDcNEhKrTegwOFTnvFKD5f_R43ww:1q16dm:HKN9H-0CvJ7K6GEU0h4qB3hSiLQ3aE-iBJoPCkTpkM8	2023-06-05 14:36:02.990756+00
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 56, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: autoria_cars_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.autoria_cars_id_seq', 92, true);


--
-- Name: autoria_task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.autoria_task_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 5, true);


--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.django_celery_beat_clockedschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.django_celery_beat_crontabschedule_id_seq', 1, true);


--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.django_celery_beat_intervalschedule_id_seq', 2, true);


--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.django_celery_beat_periodictask_id_seq', 4, true);


--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.django_celery_beat_solarschedule_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 14, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 41, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: autoria_cars autoria_cars_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.autoria_cars
    ADD CONSTRAINT autoria_cars_pkey PRIMARY KEY (id);


--
-- Name: autoria_cars autoria_cars_url_key; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.autoria_cars
    ADD CONSTRAINT autoria_cars_url_key UNIQUE (url);


--
-- Name: autoria_task autoria_task_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.autoria_task
    ADD CONSTRAINT autoria_task_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_clockedschedule django_celery_beat_clockedschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_celery_beat_clockedschedule
    ADD CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_crontabschedule django_celery_beat_crontabschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_celery_beat_crontabschedule
    ADD CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_intervalschedule django_celery_beat_intervalschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_celery_beat_intervalschedule
    ADD CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_name_key; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictasks django_celery_beat_periodictasks_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_celery_beat_periodictasks
    ADD CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solarschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: autoria_cars_url_2ac8e4c5_like; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX autoria_cars_url_2ac8e4c5_like ON public.autoria_cars USING btree (url varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_celery_beat_periodictask_clocked_id_47a69f82; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);


--
-- Name: django_celery_beat_periodictask_crontab_id_d3cba168; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);


--
-- Name: django_celery_beat_periodictask_interval_id_a8ca27da; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);


--
-- Name: django_celery_beat_periodictask_name_265a36b7_like; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON public.django_celery_beat_periodictask USING btree (name varchar_pattern_ops);


--
-- Name: django_celery_beat_periodictask_solar_id_a87ce72c; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_clocked_id_47a69f82_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id) REFERENCES public.django_celery_beat_clockedschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_crontab_id_d3cba168_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id) REFERENCES public.django_celery_beat_crontabschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_interval_id_a8ca27da_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id) REFERENCES public.django_celery_beat_intervalschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_solar_id_a87ce72c_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id) REFERENCES public.django_celery_beat_solarschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

