version: '3.7'

services:
  server:
    container_name: server
    build:
      context: ././
      dockerfile: server.Dockerfile
    restart: always
    volumes:
      - static_volume:/static
    ports:
      - "51117:51117"
    env_file:
      - .env
    networks:
      - test_proj_db-net

  nginx-server:
    container_name: nginx-server
    build:
      context: ././
      dockerfile: nginx.Dockerfile
    volumes:
      - static_volume:/static
    ports:
      - "1337:80"
    depends_on:
      - server
    env_file:
      - .env
    networks:
      - test_proj_db-net

  celery-manager-worker:
    container_name: celery-manager-worker
    build:
      context: ././
      dockerfile: celery.Dockerfile
    command: celery --app server worker -Q manager_task -c 1 --loglevel=info
    depends_on:
      - server
    env_file:
      - .env
    networks:
      - test_proj_db-net

  celery-db-worker:
    container_name: celery-db-worker
    build:
      context: ././
      dockerfile: celery.Dockerfile
    command: celery -A server worker -B -Q car_db_saver -l INFO -c 1
    depends_on:
      - server
    env_file:
      - .env
    networks:
      - test_proj_db-net

  celery-beat-worker:
    container_name: celery-beat-worker
    build:
      context: ././
      dockerfile: celery.Dockerfile
    command: celery --app server beat --loglevel=info
    depends_on:
      - server
    env_file:
      - .env
    networks:
      - test_proj_db-net

  celery-page-worker:
    container_name: celery-page-worker
    build:
      context: ././
      dockerfile: celery.Dockerfile
    command: celery -A server worker -B -Q car_page_scraper -l INFO -c 5
    depends_on:
      - server
    env_file:
      - .env
    networks:
      - test_proj_db-net

  celery-spreadsheets-worker:
    container_name: celery-spreadsheets-worker
    build:
      context: ././
      dockerfile: celery.Dockerfile
    command: celery -A server worker -B -Q spreadsheets_worker -l INFO -c 1
    depends_on:
      - server
    env_file:
      - .env
    networks:
      - test_proj_db-net

networks:
  test_proj_db-net:
    external: true


volumes:
  static_volume: