# Generated by Django 4.2.1 on 2023-05-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_number',
            field=models.CharField(null=True),
        ),
    ]
