# Generated by Django 4.2.1 on 2023-05-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoria', '0002_alter_cars_car_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='image_url',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='profile_name',
            field=models.CharField(null=True),
        ),
    ]
