# Generated by Django 4.2.1 on 2023-05-18 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('url', models.CharField(unique=True)),
                ('profile_name', models.CharField()),
                ('phone_number', models.CharField()),
                ('title', models.CharField()),
                ('price', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('image_url', models.CharField()),
                ('image_count', models.IntegerField()),
                ('car_number', models.IntegerField(null=True)),
                ('datetime_crawling', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
